name = "corretoracorporate"
compatibility_date = "2026-02-14"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "corretoracorporate-db"
database_id = "728ee55c-d607-4846-969e-741a4fd0afb2"
